#############################################################################
# Makefile for building: bin/Parser
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sa. Jan 28 22:03:34 2017
# Project:  Parser.pro
# Template: app
# Command: /home/robbe/Enthought/Canopy_64bit/User/bin/qmake -o Makefile Parser.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/linux-g++-64 -I. -I../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/include/QtCore -I../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/include/QtGui -I../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/include -Igenerated_files -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/vagrant/pisi/tmp/Qt-4.8.7-4/usr/lib
LIBS          = $(SUBLIBS)  -L/home/robbe/Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/lib -lQtGui -L/home/vagrant/src/buildsystem-git/build/master-env -L/home/vagrant/src/buildsystem-git/build/master-env/lib -L/home/vagrant/pisi/tmp/Qt-4.8.7-4/usr/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/robbe/Enthought/Canopy_64bit/User/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = generated_files/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		CYK.cpp \
		Grammar.cpp \
		Lexer.cpp \
		ll1parser.cpp \
		Node.cpp \
		ParseTree.cpp generated_files/moc_mainwindow.cpp
OBJECTS       = generated_files/main.o \
		generated_files/mainwindow.o \
		generated_files/CYK.o \
		generated_files/Grammar.o \
		generated_files/Lexer.o \
		generated_files/ll1parser.o \
		generated_files/Node.o \
		generated_files/ParseTree.o \
		generated_files/moc_mainwindow.o
DIST          = ../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/unix.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/linux.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/gcc-base.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/gcc-base-unix.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/g++-base.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/g++-unix.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/qconfig.pri \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/modules/qt_webkit_version.pri \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt_functions.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt_config.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/exclusive_builds.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/default_pre.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/release.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/default_post.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/shared.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/warn_on.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/unix/thread.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/moc.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/resources.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/uic.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/yacc.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/lex.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/include_source_dir.prf \
		Parser.pro
QMAKE_TARGET  = Parser
DESTDIR       = bin/
TARGET        = bin/Parser

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Parser.pro  ../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/linux-g++-64/qmake.conf ../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/unix.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/linux.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/gcc-base.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/gcc-base-unix.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/g++-base.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/g++-unix.conf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/qconfig.pri \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/modules/qt_webkit_version.pri \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt_functions.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt_config.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/exclusive_builds.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/default_pre.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/release.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/default_post.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/shared.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/warn_on.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/unix/thread.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/moc.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/resources.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/uic.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/yacc.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/lex.prf \
		../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/include_source_dir.prf \
		/home/robbe/Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/lib/libQtGui.prl \
		/home/robbe/Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/lib/libQtCore.prl
	$(QMAKE) -o Makefile Parser.pro
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/unix.conf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/linux.conf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/gcc-base.conf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/gcc-base-unix.conf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/g++-base.conf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/common/g++-unix.conf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/qconfig.pri:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/modules/qt_webkit_version.pri:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt_functions.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt_config.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/exclusive_builds.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/default_pre.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/release.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/default_post.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/shared.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/warn_on.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/qt.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/unix/thread.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/moc.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/resources.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/uic.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/yacc.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/lex.prf:
../../../Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/mkspecs/features/include_source_dir.prf:
/home/robbe/Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/lib/libQtGui.prl:
/home/robbe/Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Parser.pro

dist: 
	@$(CHK_DIR_EXISTS) generated_files/Parser1.0.0 || $(MKDIR) generated_files/Parser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) generated_files/Parser1.0.0/ && $(COPY_FILE) --parents mainwindow.h CYK.h Grammar.h Lexer.h ll1parser.h Node.h ParseTree.h generated_files/Parser1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp CYK.cpp Grammar.cpp Lexer.cpp ll1parser.cpp Node.cpp ParseTree.cpp generated_files/Parser1.0.0/ && $(COPY_FILE) --parents mainwindow.ui generated_files/Parser1.0.0/ && (cd `dirname generated_files/Parser1.0.0` && $(TAR) Parser1.0.0.tar Parser1.0.0 && $(COMPRESS) Parser1.0.0.tar) && $(MOVE) `dirname generated_files/Parser1.0.0`/Parser1.0.0.tar.gz . && $(DEL_FILE) -r generated_files/Parser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: generated_files/moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) generated_files/moc_mainwindow.cpp
generated_files/moc_mainwindow.cpp: Grammar.h \
		ParseTree.h \
		Node.h \
		CYK.h \
		ll1parser.h \
		mainwindow.h
	/home/robbe/Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o generated_files/moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/robbe/Canopy/appdata/canopy-1.7.4.3348.rh5-x86_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

generated_files/main.o: main.cpp mainwindow.h \
		Grammar.h \
		ParseTree.h \
		Node.h \
		CYK.h \
		ll1parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/main.o main.cpp

generated_files/mainwindow.o: mainwindow.cpp mainwindow.h \
		Grammar.h \
		ParseTree.h \
		Node.h \
		CYK.h \
		ll1parser.h \
		ui_mainwindow.h \
		Lexer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/mainwindow.o mainwindow.cpp

generated_files/CYK.o: CYK.cpp CYK.h \
		Grammar.h \
		ParseTree.h \
		Node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/CYK.o CYK.cpp

generated_files/Grammar.o: Grammar.cpp Grammar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/Grammar.o Grammar.cpp

generated_files/Lexer.o: Lexer.cpp Lexer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/Lexer.o Lexer.cpp

generated_files/ll1parser.o: ll1parser.cpp ll1parser.h \
		Grammar.h \
		ParseTree.h \
		Node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/ll1parser.o ll1parser.cpp

generated_files/Node.o: Node.cpp Node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/Node.o Node.cpp

generated_files/ParseTree.o: ParseTree.cpp ParseTree.h \
		Node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/ParseTree.o ParseTree.cpp

generated_files/moc_mainwindow.o: generated_files/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated_files/moc_mainwindow.o generated_files/moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

